// Downloads the tax invoice PDF generated by the backend (server-side,
// using real seller details + a Postgres-backed invoice record) instead of
// building one locally. This keeps the customer's invoice identical to the
// one admins see in the admin panel and avoids maintaining two separate
// invoice layouts/seller configs.
import 'dart:io';
import 'dart:typed_data';

import 'package:http/http.dart' as http;
import 'package:media_store_plus/media_store_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';

import '../models/order_model.dart';
import '../services/api_service.dart';
import 'download_notification_service.dart';

class InvoiceGenerator {
  /// Fetches the invoice PDF bytes for [order] from the backend
  /// (GET /orders/:id/invoice/pdf). Throws if the request fails or the
  /// invoice isn't available yet (e.g. payment not confirmed).
  static Future<Uint8List> fetchInvoicePdf(Order order) async {
    final headers = await ApiService.getHeaders();
    final response = await http
        .get(
          Uri.parse('${ApiService.baseUrl}/orders/${order.id}/invoice/pdf'),
          headers: headers,
        )
        .timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('Invoice not available (status ${response.statusCode})');
    }
    return response.bodyBytes;
  }

  /// Downloads the invoice PDF and saves it to the phone's public Downloads
  /// folder (Android), showing a "Download complete" notification that
  /// opens the file on tap. On platforms without a public Downloads folder
  /// (iOS/desktop), falls back to the share/print sheet.
  ///
  /// Returns true if the file was saved/shared successfully.
  static Future<bool> downloadInvoice({
    required Order order,
    required String customerName,
  }) async {
    final bytes = await fetchInvoicePdf(order);
    final fileName = 'Invoice_Order${order.id}.pdf';

    if (Platform.isAndroid) {
      // media_store_plus needs the file to exist somewhere first (e.g. app's
      // temp folder); it then copies it into the public Downloads folder via
      // MediaStore and deletes nothing on our side - we clean up ourselves.
      final tempDir = await getTemporaryDirectory();
      final tempFile = File('${tempDir.path}/$fileName');
      await tempFile.writeAsBytes(bytes, flush: true);

      final mediaStore = MediaStore();
      SaveInfo? saveInfo;
      try {
        saveInfo = await mediaStore.saveFile(
          tempFilePath: tempFile.path,
          dirType: DirType.download,
          dirName: DirName.download,
        );
      } finally {
        if (await tempFile.exists()) {
          await tempFile.delete();
        }
      }

      if (saveInfo == null) {
        return false;
      }

      // Try to resolve a real filesystem path so tapping the notification
      // can open the file directly with open_filex.
      final filePath = await mediaStore.getFilePathFromUri(
        uriString: saveInfo.uri.toString(),
      );
      final openablePath = filePath ?? saveInfo.uri.toString();

      await DownloadNotificationService.showDownloadComplete(
        fileName: saveInfo.name,
        filePath: openablePath,
      );

      return true;
    } else {
      await Printing.sharePdf(bytes: bytes, filename: fileName);
      return true;
    }
  }
}
