// Downloads the tax invoice PDF generated by the backend (server-side,
// using real seller details + a Postgres-backed invoice record) instead of
// building one locally. This keeps the customer's invoice identical to the
// one admins see in the admin panel and avoids maintaining two separate
// invoice layouts/seller configs.
import 'dart:io';
import 'dart:typed_data';

import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'package:printing/printing.dart';

import '../models/order_model.dart';
import '../services/api_service.dart';
import 'download_notification_service.dart';

class InvoiceGenerator {
  /// Fetches the invoice PDF bytes for [order] from the backend
  /// (GET /orders/:id/invoice/pdf). Throws if the request fails or the
  /// invoice isn't available yet (e.g. payment not confirmed).
  static Future<Uint8List> fetchInvoicePdf(Order order) async {
    final headers = await ApiService.getHeaders();
    final response = await http
        .get(
          Uri.parse('${ApiService.baseUrl}/orders/${order.id}/invoice/pdf'),
          headers: headers,
        )
        .timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('Invoice not available (status ${response.statusCode})');
    }
    return response.bodyBytes;
  }

  /// Downloads the invoice PDF and lets the user save it via the native
  /// "Save As" picker (Android/iOS/desktop). This avoids MediaStore/scoped
  /// storage permission quirks entirely - no storage permission is needed
  /// because the OS handles the write itself once the user picks a
  /// location. Falls back to the share/print sheet if the user cancels the
  /// picker on platforms where that makes sense.
  /// Returns true if the file was saved/shared successfully.
  static Future<bool> downloadInvoice({
    required Order order,
    required String customerName,
  }) async {
    final bytes = await fetchInvoicePdf(order);
    final fileName = 'Invoice_Order${order.id}_${DateTime.now().millisecondsSinceEpoch}.pdf';

    if (Platform.isAndroid || Platform.isIOS) {
      String? savedPath;
      try {
        savedPath = await FilePicker.platform.saveFile(
          dialogTitle: 'Save Invoice',
          fileName: fileName,
          bytes: bytes,
          type: FileType.custom,
          allowedExtensions: ['pdf'],
        );
      } catch (pickerError) {
        throw Exception('Save failed: $pickerError');
      }

      if (savedPath == null) {
        // User cancelled the save dialog - not an error, just no-op.
        return false;
      }


      // Open the invoice immediately after saving, Zepto-style, using the
      // bytes already in memory. This avoids re-reading the file from disk
      // (which fails with EACCES under scoped storage) and gives an
      // instant native PDF preview inside the app.
      await Printing.layoutPdf(onLayout: (_) async => bytes, name: fileName);
      await DownloadNotificationService.showDownloadComplete(
        fileName: fileName,
        filePath: savedPath,
      );

      return true;
    } else {
      await Printing.sharePdf(bytes: bytes, filename: fileName);
      return true;
    }
  }
}


